### ISSUE TITLE
tabbar 突出的按钮，突出部分不能响应事件呀

### ISSUE THREAD

**Issue by Andyjicw** [zonghongyan/EVNEstorePlatform#1]
<img width="375" alt="qq20170228-140408 2x" src="https://cloud.githubusercontent.com/assets/9671851/23393606/f8299c2e-fdbe-11e6-9eb9-2a81b0e952ae.png">

**Comment by zonghongyan** [comment]
多谢，新版本已做调整。

**Comment by zonghongyan** [comment]
[modify tabbar](https://github.com/zonghongyan/EVNEstorePlatform/commit/879cc2d32fe792a0102d4f93364c7151e71dbbbf)
